In [1]:
import numpy as np
from kmodes import kmodes
import pandas as pd

In [2]:
data = pd.read_csv('budd_new_22_6_18.csv', index_col= 0 )

In [3]:
data

gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
0         0             0                     0     3.50            3.0   
1         0             1                     0     3.50            3.0   
2         1             1                     0     1.80            3.0   
3         0             2                     0     3.50            5.0   
4         0             3                     0     2.00           10.0   
5         1             4                     0     2.80            3.0   
6         0             1                     0     3.00           10.0   
7         1             0                     0     3.50            5.0   
8         0             3                     0     0.60            3.0   
9         0             4                     0     2.50            3.0   
10        0             0                     0     2.50            1.0   
11        0             5                     0     0.80           10.0   
12        0             1                     0     0.00            3.0   
13        0             6                     0     0.00            5.0   
14        1             7                     0     5.00            1.0   
15        1             4                     0     0.00            3.0   
16        0             3                     0     3.50            5.0   
17        0             8                     0     1.00            3.0   
18        0             6                     0     0.00            5.0   
19        0             9                     0     0.30            3.0   
20        0             1                     0     0.00            3.0   
21        0            10                     0     1.80            5.0   
22        0             0                     0     0.00            5.0   
23        0             1                     0     2.00            5.0   
24        0             0                     0     0.40            3.0   
25        0             4                     0     2.20            5.0   
26        0             4                     0     0.00            5.0   
27        0             0                     0     0.30            5.0   
28        0             4                     0     0.00            5.0   
29        0            11                     1     0.00            5.0   
..      ...           ...                   ...      ...            ...   
492       0             4                     0     4.00            5.0   
493       0             6                     0     1.00            3.0   
494       1             9                     0     0.00            3.0   
495       0             0                     0     0.00            3.0   
496       0             0                     0     0.40            1.0   
497       0             0                     0     1.00            5.0   
498       0             1                     0     1.08            1.0   
499       0            17                     0     1.00            1.0   
500       0            51                     0     0.00            3.0   
501       0             9                     0     6.00            1.0   
502       0             5                     0     0.30           10.0   
503       0            16                     0     1.00            3.0   
504       0            18                     0     0.00            5.0   
505       1            81                     0     0.00            3.0   
506       0            18                     0     0.00            3.0   
507       0             0                     0     0.00            3.0   
508       1             0                     0     3.00            3.0   
509       0            23                     0     3.00            1.0   
510       0            82                     0     4.00            3.0   
511       0            83                     0     2.00            3.0   
512       0             5                     0     0.00           10.0   
513       0             3     

###  Keeping male and female separate

In [9]:
f_data = data.loc[data['gender'] == 1]      #Females

In [10]:
m_data = data.loc[data['gender'] == 0]    #Males

In [11]:
m_data

gender  current_city  open_to_other_branch   work_ex  dist_from_uni  \
0         0             0                     0  3.500000       3.000000   
1         0             1                     0  3.500000       3.000000   
3         0             2                     0  3.500000       5.000000   
4         0             3                     0  2.000000      10.000000   
6         0             1                     0  3.000000      10.000000   
8         0             3                     0  0.600000       3.000000   
9         0             4                     0  2.500000       3.000000   
10        0             0                     0  2.500000       1.000000   
11        0             5                     0  0.800000      10.000000   
12        0             1                     0  0.000000       3.000000   
13        0             6                     0  0.000000       5.000000   
16        0             3                     0  3.500000       5.000000   
17        0             8                     0  1.000000       3.000000   
18        0             6                     0  0.000000       5.000000   
19        0             9                     0  0.300000       3.000000   
20        0             1                     0  0.000000       3.000000   
21        0            10                     0  1.800000       5.000000   
22        0             0                     0  0.000000       5.000000   
23        0             1                     0  2.000000       5.000000   
24        0             0                     0  0.400000       3.000000   
25        0             4                     0  2.200000       5.000000   
26        0             4                     0  0.000000       5.000000   
27        0             0                     0  0.300000       5.000000   
28        0             4                     0  0.000000       5.000000   
29        0            11                     1  0.000000       5.000000   
30        0             3                     0  3.000000       3.000000   
31        0             1                     1  3.500000       5.000000   
32        0             6                     0  1.000000       5.000000   
33        0             3                     0  0.000000       5.000000   
35        0             0                     0  1.800000      10.000000   
..      ...           ...                   ...       ...            ...   
487       0             3                     0  1.360053       4.046784   
488       0            50                     0  0.000000       3.000000   
489       0             0                     0  0.000000       3.000000   
491       0            80                     0  9.000000       3.000000   
492       0             4                     0  4.000000       5.000000   
493       0             6                     0  1.000000       3.000000   
495       0             0                     0  0.000000       3.000000   
496       0             0                     0  0.400000       1.000000   
497       0             0                     0  1.000000       5.000000   
498       0             1                     0  1.080000       1.000000   
499       0            17                     0  1.000000       1.000000   
500       0            51                     0  0.000000       3.000000   
501       0             9                     0  6.000000       1.000000   
502       0             5                     0  0.300000      10.000000   
503       0            16                     0  1.000000       3.000000   
504       0            18                     0  0.000000       5.000000   
506       0            18                     0  0.000000       3.000000   
507       0             0                     0  0.000000       3.000000   
509       0            23                     0  3.000000       1.000000   
510       0            82                     0  4.000000       3.000000   
511       0            83                     0  2.00

In [12]:
def similarity_score(x, y):
    score = 0.0
    for i in range(len(x)):
        if x[i] == y[i]: score+=1
    return(score)

In [18]:
similarity_score(m_data.iloc[0], m_data.iloc[200])

26.0

In [21]:
m_data.shape

(401, 32)

In [25]:
simi_mat = np.zeros((m_data.shape[0], m_data.shape[0]))

In [26]:
for i in range(len(m_data)):
    for j in range(i, len(m_data)):
        simi_mat[i,j] = similarity_score(m_data.iloc[i], m_data.iloc[j])

In [27]:
simi_mat

array([[32., 26., 24., ..., 23., 21., 25.],
       [ 0., 32., 27., ..., 24., 19., 20.],
       [ 0.,  0., 32., ..., 24., 20., 22.],
       ...,
       [ 0.,  0.,  0., ..., 32., 21., 20.],
       [ 0.,  0.,  0., ...,  0., 32., 24.],
       [ 0.,  0.,  0., ...,  0.,  0., 32.]])

In [41]:
top_10_peruser = np.zeros((len(simi_mat), 10))
for i, row in enumerate(simi_mat):
    top_10_peruser[i, :] = np.argsort(-row)[1:11]

In [42]:
top_10_peruser

array([[382., 106., 394., ..., 196.,  27., 318.],
       [105., 335., 314., ...,  46.,  31., 103.],
       [ 11., 359.,  99., ...,  91., 131., 140.],
       ...,
       [399., 400., 396., ..., 267., 266., 265.],
       [400., 397., 271., ..., 266., 265., 264.],
       [272., 271., 270., ..., 265., 264., 263.]])

In [44]:
for j in top_10_peruser[0]:
    print(m_data.loc[j])

gender                                           0.0
current_city                                     4.0
open_to_other_branch                             0.0
work_ex                                          2.8
dist_from_uni                                    3.0
rent_budget                                    450.0
alcohol                                          0.0
smoking                                          0.0
food_pref                                        0.0
cul_skills                                       1.0
looking_for_roommate                             1.0
MS Biotechnology                                 0.0
MS Civil Engineering                             0.0
MS Computer Science                              1.0
MS Computer Systems Engineering                  0.0
MS Data Science                                  0.0
MS Electrical and Computer Engineering           0.0
MS Energy Systems                                0.0
MS Engineering Management                     

In [45]:
m_data.ix[top_10_peruser[0]]

C:\Users\Siddhesh Acharekar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
382.0       0             4                     0      2.8            3.0   
106.0       0             3                     0      1.5            3.0   
394.0       0             0                     0      5.0            3.0   
120.0       0            32                     0      0.5            3.0   
254.0       0            45                     0      9.0            3.0   
79.0        0             3                     0      5.0            3.0   
26.0        0             4                     0      0.0            5.0   
196.0       0            38                     0      0.0            5.0   
27.0        0             0                     0      0.3            5.0   
318.0       0             6                     0      0.0            5.0   

       rent_budget  alcohol  smoking  food_pref  cul_skills   ...    \
382.0          450        0        0          0           1   ...     
106.0          400        1        1          1           0   ...     
394.0          500        0        0          0           1   ...     
120.0          550        0        1          1           0   ...     
254.0         1000        0        0          0           0   ...     
79.0           450        0        0          0           0   ...     
26.0           550        0        1          0           0   ...     
196.0          700        0        0          0           0   ...     
27.0           500        0        0          0           1   ...     
318.0          700        0        0          0           0   ...     

       MS Mechanical Engineering  MS Project Management  Others  hall_yes_no  \
382.0                          0                      0       0            1   
106.0                          0                      0       1            0   
394.0                          0                      0       0            1   
120.0                          0                      0       0            0   
254.0                          0                      0       0            0   
79.0                           1                      0       0            0   
26.0                           0                      0       0            1   
196.0                          0                      0       0            0   
27.0                           0                      0       0            0   
318.0                          0                      0       0            0   

       max_ppr  bhk_1  bhk_2  bhk_3  bhk_4  studio  
382.0      3.0      1      1      1      0       0  
106.0      3.0      1      1      0      0       1  
394.0      2.0      1      1      0      0       1  
120.0      4.0      1      1      0      0       1  
254.0      1.0      1      1      1      1       1  
79.0       3.0      1      1      0      0       1  
26.0       4.0      1      1      1      1       0  
196.0      4.0      0      1      1      0       0  
27.0       2.0      1      1      1      1       0  
318.0      3.0      1      1      1      1       1  

[10 rows x 32 columns]

In [35]:
np.argsort(-np.array([0,1,2,3,4]))

array([4, 3, 2, 1, 0], dtype=int64)

In [11]:
from kmodes.kmodes import KModes

# random categorical data
data = np.random.choice(20, (100, 10))

km = KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 25, cost: 799.0
Run 1, iteration: 2/100, moves: 3, cost: 799.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 21, cost: 805.0
Run 2, iteration: 2/100, moves: 0, cost: 805.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 24, cost: 788.0
Run 3, iteration: 2/100, moves: 4, cost: 788.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 14, cost: 799.0
Run 4, iteration: 2/100, moves: 0, cost: 799.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 19, cost: 796.0
Run 5, iteration: 2/100, moves: 2, cost: 797.0
Best run was number 3
[[ 5 18  2  9 11 19  7  3  9 16]
 [ 1 18  9 19  7 11 16  4  7  5]
 [15 19  8  7 17  9 17 13  0 11]
 [ 1

In [12]:
km.cluster_centroids_

array([[ 5, 18,  2,  9, 11, 19,  7,  3,  9, 16],
       [ 1, 18,  9, 19,  7, 11, 16,  4,  7,  5],
       [15, 19,  8,  7, 17,  9, 17, 13,  0, 11],
       [ 1,  0,  5,  7,  6,  4,  8,  8, 13,  4]])

In [17]:
# random categorical data
km = KModes(n_clusters=6, init='Huang', n_init=5, verbose=1)
clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 217, cost: 3156.0
Run 1, iteration: 2/100, moves: 15, cost: 3136.0
Run 1, iteration: 3/100, moves: 15, cost: 3136.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 210, cost: 3147.0
Run 2, iteration: 2/100, moves: 0, cost: 3147.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 235, cost: 3136.0
Run 3, iteration: 2/100, moves: 27, cost: 3136.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 214, cost: 3161.0
Run 4, iteration: 2/100, moves: 43, cost: 3161.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 214, cost: 3179.0
Run 5, iteration: 2/100, moves: 20, cost: 3179.0
Best run was number 1
[[  0.   0.   0.   0.   3. 700.   0

In [23]:
km.cat_dissim()

TypeError: matching_dissim() missing 2 required positional arguments: 'a' and 'b'

# Custom KModes function