# Treating categorical and continuous variables separately.

In [119]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.preprocessing import StandardScaler
from scipy.spatial.distance import hamming

In [187]:
og_sheet = pd.read_excel('find_my_buddy.csv.xlsx', sheet_name='Buddy Sheet')

In [192]:
og_sheet['Full Name'].drop(522)

0                          Sachin Haldavanekar
1                                Sanket Saurav
2                                   Viha Bidre
3                              Sougata Dafader
4                           Athul Muralidharan
5                               Megha Suvarna 
6                                       Vishnu
7                             Srashti Kasliwal
8                                  Balakumaran
9                                       Pranav
10                        Harshil Navin Dhruve
11                        Shravan kumar reddy 
12                                Tejas Harish
13                                 Rohan Taori
14                                           Z
15                              Mrunal Ghanwat
16                   Varun Sundar Rabindranath
17                          Kaustubh Shivdikar
18                              Pratik Devikar
19                                Saumil Patel
20                          Keerthan Bharadwaj
21           

In [197]:
meta_data = pd.read_csv('budd_new_22_6_18.csv', index_col= 0)

In [198]:
meta_data.columns

Index(['gender', 'current_city', 'open_to_other_branch', 'work_ex',
       'dist_from_uni', 'rent_budget', 'alcohol', 'smoking', 'food_pref',
       'cul_skills', 'looking_for_roommate', 'MS Biotechnology',
       'MS Civil Engineering', 'MS Computer Science',
       'MS Computer Systems Engineering', 'MS Data Science',
       'MS Electrical and Computer Engineering', 'MS Energy Systems',
       'MS Engineering Management', 'MS Industrial Engineering',
       'MS Information Assurance and Cyber Security', 'MS Information Systems',
       'MS Mechanical Engineering', 'MS Project Management', 'Others',
       'hall_yes_no', 'max_ppr', 'bhk_1', 'bhk_2', 'bhk_3', 'bhk_4', 'studio'],
      dtype='object')

In [199]:
meta_data = meta_data.drop(labels=['looking_for_roommate', 'Others'], axis = 1)

In [204]:
name_list = list(og_sheet['Full Name'].drop(522))

In [205]:
name_list

['Sachin Haldavanekar',
 'Sanket Saurav',
 'Viha Bidre',
 'Sougata Dafader',
 'Athul Muralidharan',
 'Megha Suvarna ',
 'Vishnu',
 'Srashti Kasliwal',
 'Balakumaran',
 'Pranav',
 'Harshil Navin Dhruve',
 'Shravan kumar reddy ',
 'Tejas Harish',
 'Rohan Taori',
 'Z',
 'Mrunal Ghanwat',
 'Varun Sundar Rabindranath',
 'Kaustubh Shivdikar',
 'Pratik Devikar',
 'Saumil Patel',
 'Keerthan Bharadwaj',
 'Sreejith',
 'Rushaabh Saliya',
 'Srinidhi Shankar',
 'Harsh Sheth',
 'Nipun Midha',
 'Varad',
 'Chaitanya Joshi',
 'Cyril Mathew ',
 'VYOM RAJ',
 'Bharathwaj',
 'Sibendu Dey',
 'Akshat Shukla',
 'Pragadeesh Suresh babu',
 'Samruddhi Pai Kakode',
 'Gaurav Gandhi',
 'VENKATA SAI TARUN UPPALA',
 'Grishma Thakkar',
 'Abhinn Ankit',
 'Chirayu Desai',
 'Abhishek Ahuja',
 'Ninad Kanetkar',
 'Prasanna Kumar Challa',
 'Sagar',
 'Saurabh',
 'Aman Mankar',
 'Anup Srivastava',
 'ganesh surada',
 'Naman Bhargava',
 'Vikas Singh',
 'Prashant Reddy',
 'Poojith Shankar Shetty',
 'Prashant Reddy',
 'Vipul Shar

In [206]:
meta_data

gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
0         0             0                     0     3.50            3.0   
1         0             1                     0     3.50            3.0   
2         1             1                     0     1.80            3.0   
3         0             2                     0     3.50            5.0   
4         0             3                     0     2.00           10.0   
5         1             4                     0     2.80            3.0   
6         0             1                     0     3.00           10.0   
7         1             0                     0     3.50            5.0   
8         0             3                     0     0.60            3.0   
9         0             4                     0     2.50            3.0   
10        0             0                     0     2.50            1.0   
11        0             5                     0     0.80           10.0   
12        0             1                     0     0.00            3.0   
13        0             6                     0     0.00            5.0   
14        1             7                     0     5.00            1.0   
15        1             4                     0     0.00            3.0   
16        0             3                     0     3.50            5.0   
17        0             8                     0     1.00            3.0   
18        0             6                     0     0.00            5.0   
19        0             9                     0     0.30            3.0   
20        0             1                     0     0.00            3.0   
21        0            10                     0     1.80            5.0   
22        0             0                     0     0.00            5.0   
23        0             1                     0     2.00            5.0   
24        0             0                     0     0.40            3.0   
25        0             4                     0     2.20            5.0   
26        0             4                     0     0.00            5.0   
27        0             0                     0     0.30            5.0   
28        0             4                     0     0.00            5.0   
29        0            11                     1     0.00            5.0   
..      ...           ...                   ...      ...            ...   
492       0             4                     0     4.00            5.0   
493       0             6                     0     1.00            3.0   
494       1             9                     0     0.00            3.0   
495       0             0                     0     0.00            3.0   
496       0             0                     0     0.40            1.0   
497       0             0                     0     1.00            5.0   
498       0             1                     0     1.08            1.0   
499       0            17                     0     1.00            1.0   
500       0            51                     0     0.00            3.0   
501       0             9                     0     6.00            1.0   
502       0             5                     0     0.30           10.0   
503       0            16                     0     1.00            3.0   
504       0            18                     0     0.00            5.0   
505       1            81                     0     0.00            3.0   
506       0            18                     0     0.00            3.0   
507       0             0                     0     0.00            3.0   
508       1             0                     0     3.00            3.0   
509       0            23                     0     3.00            1.0   
510       0            82                     0     4.00            3.0   
511       0            83                     0     2.00            3.0   
512       0             5                     0     0.00           10.0   
513       0             3     

## Test area

In [7]:
test_person = meta_data.iloc[[65]]    # Paarth Kotak

In [8]:
test_person

gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
65       0             0                     0      2.0            3.0   

    rent_budget  alcohol  smoking  food_pref  cul_skills   ...    \
65          700        0        1          1           0   ...     

    MS Information Systems  MS Mechanical Engineering  MS Project Management  \
65                       0                          0                      0   

    hall_yes_no  max_ppr  bhk_1  bhk_2  bhk_3  bhk_4  studio  
65            0      4.0      0      1      0      0       0  

[1 rows x 30 columns]

In [116]:
meta_data[meta_data['gender'] == 0].iloc[[57]]

gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
65       0             0                     0      2.0            3.0   

    rent_budget  alcohol  smoking  food_pref  cul_skills   ...    \
65          700        0        1          1           0   ...     

    MS Information Systems  MS Mechanical Engineering  MS Project Management  \
65                       0                          0                      0   

    hall_yes_no  max_ppr  bhk_1  bhk_2  bhk_3  bhk_4  studio  
65            0      4.0      0      1      0      0       0  

[1 rows x 30 columns]

In [47]:
test_p_cont = np.array(get_cont_cat(test_person, 'cont'))

In [48]:
db_cont = np.array(get_cont_cat(meta_data, 'cont'))

In [49]:
test_p_cont.shape

(1, 3)

In [50]:
db_cont.shape

(522, 3)

In [53]:
test_p_cont

array([[  2.,   3., 700.]])

In [56]:
euclidean_distances(test_p_cont, db_cont).shape

(1, 522)

In [22]:
def get_cont_cat(dataframe, var_type):
    '''
    Function to split and return the dataframe by the variable type needed.
    
    I/P:
    'dataframe': whole data as a pandas dataframe
    'var_type': variable type, "cont" or "cat", string
    
    O/P:
    'dataframe': dataframe with only columns of the needed variable type
    '''
    
    
    # Convert any series to dataframe
    if not isinstance(dataframe, pd.DataFrame):
        print('ip is not dataframe')
    cont_cols = ['work_ex', 'dist_from_uni', 'rent_budget']
    
    
    
    if var_type == 'cont':
        return dataframe[cont_cols]
    
    
    
    elif var_type == 'cat':
        return dataframe.drop(labels = cont_cols, axis = 1)
    
    
    
    else: raise ValueError('Variable type should be either "cont" or "cat"')

In [154]:
def get_cont_dist(person, database, metric):
    
    '''
    Function that returns a distance matrix for continuous features of the data.
    Feature normalization happens in here.
    I/P:
    'person': 1 x 3 numpy array of 1 person
    'database': (total data length) x 3 numpy array
    'metric': distance metric to be used for computation. One of: euclidean.
    
    O/P:
    'distance_matrix': 1 x (total data length) numpy array of distances
    '''
#     print('sdkfjsdkf')

    to_std = np.vstack((person, database))
    
    all_std = StandardScaler().fit_transform(to_std)
    person_std = all_std[0,:].reshape(1,-1)
    database_std = all_std[1:,:]
    
    if metric == 'euclidean':
        cont_distance_matrix = euclidean_distances(person_std, database_std)
        return cont_distance_matrix

In [155]:
def get_cat_dist(person, database, metric):
    '''
    Function that returns a distance matrix for categorical features of the data.
    I/P:
    'person': 1 x 3 numpy array of 1 person
    'database': (total data length) x 3 numpy array
    'metric': distance metric to be used for computation. One of: hamming
    
    O/P:
    'distance_matrix': 1 x (total data length) numpy array of distances
    '''
    cat_distance_matrix = []
    if metric == 'hamming':
        for index, c_row in database.iterrows():
            cat_distance_matrix.append(hamming(person, c_row))
    return(np.array(cat_distance_matrix))

In [158]:
get_cat_dist(test_cat, get_cont_cat(meta_data[meta_data['gender'] == 0], 'cat'), 'hamming')[57]

0.0

In [156]:
get_cat_dist(test_cat, get_cont_cat(meta_data, 'cat'), 'hamming')

array([0.14814815, 0.2962963 , 0.22222222, 0.2962963 , 0.18518519,
       0.22222222, 0.33333333, 0.22222222, 0.22222222, 0.25925926,
       0.07407407, 0.14814815, 0.22222222, 0.33333333, 0.25925926,
       0.25925926, 0.22222222, 0.33333333, 0.25925926, 0.18518519,
       0.18518519, 0.25925926, 0.25925926, 0.22222222, 0.37037037,
       0.25925926, 0.22222222, 0.33333333, 0.40740741, 0.2962963 ,
       0.18518519, 0.18518519, 0.14814815, 0.25925926, 0.25925926,
       0.18518519, 0.33333333, 0.18518519, 0.37037037, 0.18518519,
       0.18518519, 0.25925926, 0.2962963 , 0.2962963 , 0.22222222,
       0.25925926, 0.2962963 , 0.33333333, 0.40740741, 0.22222222,
       0.2962963 , 0.2962963 , 0.2962963 , 0.25925926, 0.14814815,
       0.25925926, 0.2962963 , 0.14814815, 0.18518519, 0.18518519,
       0.14814815, 0.22222222, 0.2962963 , 0.22222222, 0.25925926,
       0.        , 0.25925926, 0.33333333, 0.18518519, 0.25925926,
       0.25925926, 0.14814815, 0.22222222, 0.37037037, 0.33333

In [125]:
test_cat = get_cont_cat(test_person, 'cat')
test_cat2 = get_cont_cat(meta_data.iloc[[34]], 'cat')

In [128]:
hamming(test_cat, test_cat2)

0.25925925925925924

In [237]:
def findRoommate(new_person, database, n_roommates, alpha, beta):
    # Split data by gender to reduce computations
    database_g = database[database['gender'] == new_person.iloc[0]['gender']]
#     print(len(database_g))
    name_g = [name_list[i] for i in list(database_g.index)]
#     print(name_g)

    # Split new datapoint into continuous and categorical sets
    new_person_cont = get_cont_cat(new_person, 'cont')
    new_person_cat = get_cont_cat(new_person, 'cat')
    
#     print(new_person_cat.shape, new_person_cont.shape)
    
    # Split database into continuous and categorical sets
    database_cont = get_cont_cat(database_g, 'cont')
    database_cat = get_cont_cat(database_g, 'cat')
    
#     print(database_cat.shape, database_cont.shape)
    
    
    # Get distances for both continuous and categorical sets
    dist_cont = get_cont_dist(new_person_cont, database_cont, 'euclidean')
#     print(dist_cont.shape, np.argsort(dist_cont))
    
    

    dist_cat = get_cat_dist(new_person_cat, database_cat, 'hamming')
    
#     print(dist_cont + dist_cat)
    # Create final distance matrix of weighted average
    # Have to experiment with different alpha(cont_coeff) and beta(cat_coeff)
    # We good till here
    final_dist = alpha*dist_cont + beta*dist_cat
#     print(final_dist)
    # Sort the distance matrix to get top n roommates
    top_n_matches = np.argsort(final_dist)[0][1 : n_roommates + 1]
    print(top_n_matches)
    print(list(name_g[j] for j in top_n_matches))
    

In [238]:
findRoommate(test_person, meta_data, 10, 1, 1)

[215 311 357 178 186 115 113 192 142  75]
['Akash Piyush Parikh', 'Vivin Thomas Wilson', 'Gaurav Tripathi', 'Shreyansh Singh', 'Anshit Srivastava', 'Shashwat Shetty', 'Kousthubh B S', 'Ojas Phansekar', 'Adwait Joshi', 'Chirag shivnani']


In [225]:
name_list[[0,1,2]]

TypeError: list indices must be integers or slices, not list

In [35]:
test_person.iloc[0]['gender']

0.0

In [36]:
0 == 0.0

True

In [25]:
meta_data.shape

(522, 30)

In [26]:
meta_data.gender.value_counts()

0    401
1    121
Name: gender, dtype: int64